// ...existing code...
$transaction = Transaction::with(['customer', 'user', 'transactionDetails.product'])->findOrFail($id);
// ...existing code...
return view('pos.receipt', compact('transaction'));